version: '3'
services: 
  gnb1:
    image: ueransimforfree5gc:3.2.2
    container_name: gnb1
    command: 
      - gnb
    environment:
      AMF_HOSTNAME: amf
      GNB_HOSTNAME: gnb1
      MCC: '208'
      MNC: '93'
      SST: '1'
      SD: '066051'
